### ISSUE TITLE
bluebird? issues.

### ISSUE THREAD

**Issue by idkjs** [reindexio/graphql-relay-mongodb-pagination#3]
I thought I would keep powering through after the last issue. On the next [section](https://www.reindex.io/blog/relay-graphql-pagination-with-mongodb/#adding-first-and-last) after adding Article.js there is an async issue that is past my pay grade. Upon connecting and running, you get a graphiql error that looks like this:

```{"errors":[{"message":"A value undefined was yielded that could not be treated as a promise\n\n    See http://goo.gl/MqrFmX\n\nFrom coroutine:\n    at Promise.coroutine (/Users/klik/Projects/fuse-reindex-mongodb-tut/node_modules/bluebird/js/release/generators.js:194:17)\n    at Object.<anonymous> (/Users/klik/Projects/fuse-reindex-mongodb-tut/src/index.js:22:21)\n    at Module._compile (module.js:541:32)\n    at loader (/Users/klik/Projects/fuse-reindex-mongodb-tut/node_modules/babel-register/lib/node.js:144:5)\n    at Object.require.extensions.(anonymous function) [as .js] (/Users/klik/Projects/fuse-reindex-mongodb-tut/node_modules/babel-register/lib/node.js:154:7)\n    at Module.load (module.js:458:32)\n    at tryModuleLoad (module.js:417:12)\n    at Function.Module._load (module.js:409:3)\n    at Function.Module.runMain (module.js:575:10)"}]}```

I tried following the error guidance [here](http://bluebirdjs.com/docs/error-explanations.html#error-a-value-was-yielded-that-could-not-be-treated-as-a-promise) but like i said, i dont have the experience to figure out how to apply this yet. Any ideas?

Thank you.

**Comment by idkjs** [comment]
This might be related.
https://github.com/babel/babel-loader

**Comment by idkjs** [comment]
went back to it. just adding bluebird seems to do the trick. not getting additional issue right now. Thanks.
